#ifndef FILMMANAGER_DOMAIN_GLOBAL_H
#define FILMMANAGER_DOMAIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILMMANAGER_DOMAIN_LIBRARY)
#define FILMMANAGER_DOMAIN_EXPORT Q_DECL_EXPORT
#else
#define FILMMANAGER_DOMAIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FILMMANAGER_DOMAIN_GLOBAL_H
